MODEL:
    architecture: "StreamSegmentation2D"
    backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/tsm_mobilenetv2_dense_320p_1x1x8_100e_kinetics400_rgb_20210202-61135809.pth"
        clip_seg_num: 8
        shift_div: 8
        out_indices: (7, )
    neck:
        name: "AvgPoolNeck"
        num_classes: 11
        in_channels: 1280
        clip_seg_num: 8
        drop_ratio: 0.5
        need_pool: False
    head:
        name: "TCN3DHead"
        num_layers: 4
        num_f_maps: 64
        seg_in_channels: 1280
        num_classes: 11
        sample_rate: 4
    loss:
        name: "SegmentationLoss"
        num_classes: 11
        sample_rate: 4
        smooth_weight: 0.15
        ignore_index: -100

PRETRAINED: "output/MobileNetV2TSM_3D_TCN_gtea_split1/MobileNetV2TSM_3D_TCN_gtea_split1_best.pkl"

VISUALIZE:
    layer_name:
        # - "head.fc_cls"
        - "head.layers.3.norm"
    fps: 4
    batch_size: 2
    sample_rate: 4
    ignore_index: -100
    return_targets_name: None
    output_frame_size: [720, 404]
    reshape_transform: "NCTHW"
    label_path: "./data/gtea/mapping.txt"

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks", "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    config:
        name: "RawFrameStreamCAMDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 32
        clip_seg_num: 8
        sample_rate: 4

PIPELINE: #PIPELINE field
    name: "BasePipline"
    decode:
        name: "VideoDecoder"
        backend: "decord"
    sample:
        name: "VideoStreamSampler"
        is_train: False
        sample_rate: 4
        clip_seg_num: 8
        sliding_window: 32
        sample_mode: "uniform"
    transform:
        name: "VideoStreamRawFrameStoreTransform"
        transform_list:
            - Resize:
                size: [256, 320]
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.551, 0.424, 0.179]
                std: [0.133, 0.141, 0.124]