MODEL:
    architecture: "Recognition2D"
    backbone:
        name: "SLViT"
        image_size: 224
        patch_size: 32
        depth: 4
        heads: 12
        mlp_dim: 1024
        dropout: 0.3
        emb_dropout: 0.3
    neck:
    head:
        name: "TimeSformerHead"
        num_classes: 11
        clip_seg_num: 8
        sample_rate: 4
        in_channels: 1024
    loss:
        name: "RecognitionSegmentationLoss"
        label_mode: "hard"
        num_classes: 11
        sample_rate: 4
        loss_weight: 1.0
        ignore_index: -100

PRETRAINED: "output/SLViT_gtea_split1/SLViT_gtea_split1_best.pkl"

VISUALIZE:
    layer_name:
        - "head.fc_cls"
        # - "backbone.transformer.layers.3.1.fn.net.4"
    fps: 4
    batch_size: 2
    sample_rate: 4
    ignore_index: -100
    return_targets_name: None
    output_frame_size: [224, 224]

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks" , "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    config:
        name: "RawFrameStreamCAMDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 32
        clip_seg_num: 8
        sample_rate: 4

PIPELINE: #PIPELINE field
    name: "BasePipline"
    decode:
        name: "VideoDecoder"
        backend: "decord"
    sample:
        name: "VideoStreamSampler"
        is_train: False
        sample_rate: 4
        clip_seg_num: 8
        sliding_window: 32
        sample_mode: "uniform"
    transform:
        name: "VideoStreamRawFrameStoreTransform"
        transform_list:
            - Resize:
                size: [256, 320]
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.551, 0.424, 0.179]
                std: [0.133, 0.141, 0.124]
